# Настройки сервера
REMOTE_USER="ваш_пользователь"                 # Имя пользователя на сервере
REMOTE_HOST="example.com"                      # Домен или IP сервера
REMOTE_DIR="/путь/к/вашему/сайту"              # Директория сайта на сервере

# Настройки баз данных
declare -A DATABASES=(
    ["имя_базы1"]="пользователь1:пароль1"
    ["имя_базы2"]="пользователь2:пароль2"
)
